/*
 * Copyright 2015 by Nextlabs Inc.
 *
 * All rights reserved worldwide.
 * Created on May 13, 2016
 *
 */
package com.nextlabs.destiny.console.delegadmin.actions;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;

/**
 * 
 * Actions Interface for Delegated Administration
 *
 * @author aishwarya
 * @since 8.0
 *
 */
public interface DelegationModelActions {

    String VIEW_DASHBOARD = "VIEW_DASHBOARD";
    String VIEW_POLICY_FOLDER = "VIEW_POLICY_FOLDER";
    String DELETE_POLICY_FOLDER = "DELETE_POLICY_FOLDER";
    String RENAME_POLICY_FOLDER = "RENAME_POLICY_FOLDER";
    String CREATE_POLICY_FOLDER= "CREATE_POLICY_FOLDER";
    String MOVE_POLICY_FOLDER = "MOVE_POLICY_FOLDER";
    String VIEW_COMPONENT_FOLDER = "VIEW_COMPONENT_FOLDER";
    String DELETE_COMPONENT_FOLDER = "DELETE_COMPONENT_FOLDER";
    String RENAME_COMPONENT_FOLDER = "RENAME_COMPONENT_FOLDER";
    String CREATE_COMPONENT_FOLDER= "CREATE_COMPONENT_FOLDER";
    String MOVE_COMPONENT_FOLDER = "MOVE_COMPONENT_FOLDER";
	String EDIT_POLICY = "EDIT_POLICY";
    String VIEW_POLICY = "VIEW_POLICY";
    String DELETE_POLICY = "DELETE_POLICY";
    String DEPLOY_POLICY = "DEPLOY_POLICY";
    String CREATE_POLICY = "CREATE_POLICY";
    String MOVE_POLICY = "MOVE_POLICY";
    String MIGRATE_POLICY = "MIGRATE_POLICY";
    String EDIT_COMPONENT = "EDIT_COMPONENT";
    String VIEW_COMPONENT = "VIEW_COMPONENT";
    String DELETE_COMPONENT = "DELETE_COMPONENT";
    String DEPLOY_COMPONENT = "DEPLOY_COMPONENT";
    String CREATE_COMPONENT = "CREATE_COMPONENT";
    String MOVE_COMPONENT = "MOVE_COMPONENT";
    String EDIT_POLICY_MODEL = "EDIT_POLICY_MODEL";
    String VIEW_POLICY_MODEL = "VIEW_POLICY_MODEL";
    String DELETE_POLICY_MODEL = "DELETE_POLICY_MODEL";
    String DEPLOY_POLICY_MODEL = "DEPLOY_POLICY_MODEL";
    String CREATE_POLICY_MODEL = "CREATE_POLICY_MODEL";
    String MANAGE_REPORTER = "MANAGE_REPORTER";
    String VIEW_REPORTER = "VIEW_REPORTER";
    String EDIT_ADMINISTRATOR = "EDIT_ADMINISTRATOR";
    String VIEW_ADMINISTRATOR = "VIEW_ADMINISTRATOR";
    String DELETE_ADMINISTRATOR = "DELETE_ADMINISTRATOR";
    String CREATE_ADMINISTRATOR = "CREATE_ADMINISTRATOR";
    String MANAGE_DELEGATED_ADMIN = "MANAGE_DELEGATION_POLICIES";
    String MANAGE_USERS = "MANAGE_USERS";
    String CREATE_POLICY_TAG = "CREATE_POLICY_TAG";
    String CREATE_COMPONENT_TAG = "CREATE_COMPONENT_TAG";
    String CREATE_POLICY_MODEL_TAG = "CREATE_POLICY_MODEL_TAG";
    String EDIT_AUTH_MANAGEMENT = "EDIT_AUTH_MANAGEMENT";
    String VIEW_AUTH_MANAGEMENT = "VIEW_AUTH_MANAGEMENT";
    String DELETE_AUTH_MANAGEMENT = "DELETE_AUTH_MANAGEMENT";
    String CREATE_AUTH_MANAGEMENT = "CREATE_AUTH_MANAGEMENT";
    String POLICY_VALIDATOR = "POLICY_VALIDATOR";
    String ENROLLMENT_MANAGEMENT = "ENROLLMENT_MANAGEMENT";
    String MANAGE_SYSTEM_CONFIGURATION = "MANAGE_SYSTEM_CONFIGURATION";
    String MANAGE_LOGGING_CONFIGURATION = "MANAGE_LOGGING_CONFIGURATION";
    String MANAGE_SECURE_STORE = "MANAGE_SECURE_STORE";
    String MANAGE_PDP_PLUGIN = "MANAGE_PDP_PLUGIN";
    String XACML_POLICY = "XACML_POLICY";
    String VIEW_ENVIRONMENT_CONFIGURATION = "VIEW_ENVIRONMENT_CONFIGURATION";
    String DELETE_ENVIRONMENT_CONFIGURATION = "DELETE_ENVIRONMENT_CONFIGURATION";
    String CREATE_ENVIRONMENT_CONFIGURATION = "CREATE_ENVIRONMENT_CONFIGURATION";
    String EDIT_ENVIRONMENT_CONFIGURATION = "EDIT_ENVIRONMENT_CONFIGURATION";
    String MANAGE_POLICY_WORKFLOW_LEVEL = "MANAGE_POLICY_WORKFLOW_LEVEL_%s";
    String MANAGE_POLICY_CONTROLLER = "MANAGE_POLICY_CONTROLLER";
    String MANAGE_POLICY_CONTROLLER_PROFILE = "MANAGE_POLICY_CONTROLLER_PROFILE";
    String MANAGE_ICENET = "MANAGE_ICENET";

    static GrantedAuthority getAuthority(String authorityCode) {
        return new SimpleGrantedAuthority(authorityCode);
    }
}
