service:
  type: ClusterIP
image:
  repository:
  pullPolicy:
  imagePullSecret:
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 512Mi
securityContext:
  runAsUser:
  fsGroup:
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
statusCheck:
  initialDelay: 180
nextlabs:
  cc:
    configService:
      password:
    enrolledDataVolumeClaimName:
    logsVolumeClaimName:
