apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nextlabs-control-center-license
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  license.dat: |-
  {{- if .Values.global.nextlabs.cc.license }}
  {{ .Values.global.nextlabs.cc.license | indent 2 }}
  {{- else }}
  {{ .Values.nextlabs.cc.license | indent 2 }}
  {{- end }}
