apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reporter.fullname" . }}
  labels:
    {{- include "reporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "reporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "reporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- if or .Values.global.image.imagePullSecret .Values.image.imagePullSecret }}
      imagePullSecrets:
      {{- if .Values.global.image.imagePullSecret }}
      - name: {{ .Values.global.image.imagePullSecret }}
      {{- else }}
      - name: {{ .Values.image.imagePullSecret }}
      {{- end }}
      {{- end }}
      securityContext:
      {{- if .Values.global.securityContext.runAsUser }}
        {{- toYaml .Values.global.securityContext | nindent 8 }}
      {{- else }}
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      initContainers:
      - name: {{ .Release.Name }}-nextlabs-cc-reporter-wait-for-service
        image: {{ .Values.global.image.repository }}/nextlabs-control-center-wait-for-service:2020.9
        {{- if .Values.global.image.pullPolicy }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        {{- else }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- end }}
        env:
        - name: NEXTLABS_CC_WAITFOR_URL_0
          value: http://{{ .Release.Name }}-nextlabs-control-center-config-service:7443/config-service/status
        - name: NEXTLABS_CC_WAITFOR_URL_1
          value: http://{{ .Release.Name }}-nextlabs-control-center-management-server:8081/status
      containers:
      - name: {{ .Chart.Name }}
        {{- if .Values.global.image.repository }}
        image: "{{ .Values.global.image.repository }}/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
        {{- else }}
        image: "{{ .Values.image.repository }}/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
        {{- end }}
        {{- if .Values.global.image.pullPolicy }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        {{- else }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- end }}
        ports:
        - name: http-{{ .Release.Name }}-app
          containerPort: 8080
          protocol: TCP
        - name: https-{{ .Release.Name }}-web
          containerPort: 8443
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /status
            port: 8081
          {{- if .Values.global.statusCheck.initialDelay }}
          initialDelaySeconds: {{ .Values.global.statusCheck.initialDelay }}
          {{- else }}
          initialDelaySeconds: {{ .Values.statusCheck.initialDelay | default 180 }}
          {{- end }}
        readinessProbe:
          httpGet:
            path: /status
            port: 8081
          {{- if .Values.global.statusCheck.initialDelay }}
          initialDelaySeconds: {{ .Values.global.statusCheck.initialDelay }}
          {{- else }}
          initialDelaySeconds: {{ .Values.statusCheck.initialDelay | default 180 }}
          {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
        - name: NEXTLABS_CC_MANAGEMENTSERVER_HOST
          value: {{ .Release.Name }}-nextlabs-control-center-management-server
        - name: NEXTLABS_CC_SERVICE_NAME
          value: {{ .Release.Name }}-{{ .Chart.Name }}
        volumeMounts:
        - name: bootstrap-properties
          mountPath: /opt/nextlabs/control-center/server/configuration/bootstrap.properties
          subPath: bootstrap.properties
          readOnly: true
        {{- if or .Values.global.nextlabs.cc.logsVolumeClaimName .Values.nextlabs.cc.logsVolumeClaimName }}
        - name: logs
          mountPath: /opt/nextlabs/control-center/server/logs
        {{- end }}
      volumes:
      - name: bootstrap-properties
        secret:
          secretName: {{ .Release.Name }}-nextlabs-control-center-bootstrap-properties
      {{- if or .Values.global.nextlabs.cc.logsVolumeClaimName .Values.nextlabs.cc.logsVolumeClaimName }}
      - name: logs
        persistentVolumeClaim:
          {{- if .Values.global.nextlabs.cc.logsVolumeClaimName }}
          claimName: {{ .Values.global.nextlabs.cc.logsVolumeClaimName }}
          {{- else }}
          claimName: {{ .Values.nextlabs.cc.logsVolumeClaimName }}
          {{- end }}
      {{- end }}
