version: '3.7'

services:
  pgccdb:
    image: "postgres:9.5-alpine"
    ports:
      - "5432:5432"
    networks:
      - ccnet
    environment:
      - POSTGRES_USER=ccdbuser
      - POSTGRES_PASSWORD=Next1234
      - POSTGRES_DB=ccdb
    volumes:
      - "ccdb_data:/var/lib/postgresql/data"

  cc:
    image: "nextlabs-control-center:latest"
    ports:
      - "443:443"
      - "7443:7443"
      - "8443:8443"
      - "61616:61616"
      - "18080:18080"
    networks:
      - ccnet
    environment:
      - NEXTLABS_CC_DNSNAME=cc.nextlabs.local
      - NEXTLABS_CC_SERVICENAME=cc
      - NEXTLABS_CC_DB_USERNAME=ccdbuser
      - NEXTLABS_CC_DB_PASSWORD=Next1234
      - NEXTLABS_CC_DB_URL=jdbc:postgresql://pgccdb/ccdb
      - NEXTLABS_CC_DB_RETRYATTEMPTS=10
      - NEXTLABS_CC_ADMIN_PASSWORD={cipher}sddd02fe4b0e2496726307ae0147f69d3
      - NEXTLABS_CC_TYPE=COMPLETE
      - NEXTLABS_CC_MANAGEMENTSERVER_PASSWORD={cipher}sddd02fe4b0e2496726307ae0147f69d3
      - NEXTLABS_CC_COMMPROFILE_DABSLOCATION=https://cc:8443/dabs
      - NEXTLABS_CC_COMMPROFILE_HEARTBEATFREQTIME=2
      - NEXTLABS_CC_COMMPROFILE_HEARTBEATFREQTIMEUNIT=minutes
      - NEXTLABS_CC_COMMPROFILE_PUSHENABLED=true
      - NEXTLABS_CC_HEALTHCHECKSERVICE_ENABLED=true
      - NEXTLABS_CC_HEALTHCHECKSERVICE_PROTOCOL=HTTP
      - NEXTLABS_CC_SSL_KEYSTORE_PASSWORD={cipher}sddd02fe4b0e2496726307ae0147f69d3
      - NEXTLABS_CC_SSL_TRUSTSTORE_PASSWORD={cipher}sddd02fe4b0e2496726307ae0147f69d3
      - NEXTLABS_CC_SSL_CCKEYPAIRSTORE_PASSWORD={cipher}sddd02fe4b0e2496726307ae0147f69d3
      - NEXTLABS_CC_SSL_CCKEYPAIRSTORE_KEYALIAS=control_center
      - |
        NEXTLABS_CC_SSL_CCKEYPAIRSTORE_CONTENT=
        MIIKMwIBAzCCCewGCSqGSIb3DQEHAaCCCd0EggnZMIIJ1TCCBXkGCSqGSIb3DQEHAaCCBWoEggVm
        MIIFYjCCBV4GCyqGSIb3DQEMCgECoIIE+zCCBPcwKQYKKoZIhvcNAQwBAzAbBBRxVOr/SnZyff6q
        oDX+d+9K7F9UkAIDAMNQBIIEyIT6Ig0ISo0w/wnqkAjL6fm1iXIX1vkyrVmIK+jinAXam0Kie3Vt
        cAmOzVZlUvHULYvsk4/9ATNZt7syhXFQ30ki9+VXeh0ULWK3KH2ilU5ipd6b56KM/GZ8zpavXzUP
        cxFvC5un1HaXhoTZQFwPEfUBDjSOrNnC0XtpFmKa0nEO9QfRL1G6cSIgWItFpPvYHrYh3c40vpQO
        L4reDdpdTx5QfFQO6u9WQI23Rxje01bRbGHseKXkB4zgBNX686vPsCN8SRLwbVaTHGjcrW7SLsWr
        nGyRrqdblgmtev/1vvWSYd/vLsXg1vpZhkBgmg701Po/cKvp3tk50MHYXn7jubOsOHaSJq0zoGpU
        kKNhlSCCpoEX2rAJGNOvUQkMCgw8Vad7m7H/5XUON7SS39mr7aufnCBtiREKVH7zp1rqIl7tIdcY
        2C80V3eAJMuxXbWTL8U/yM/HsSLZa2AHvt45ThhKm0WfuulaDsb0eKyk+dPZQoTAd1aEPUd5hbKz
        wC/X6+tq18zNzBcdsLBbLNHdc009P3GDvOA4QR6tdRWELZp91Du1U0r6CepUMX9EHedFCeka63Xx
        AtySEzK17/DtBJ3rKk8ryrtJHL75vHI2i6FATWQPPDpWJ82H5kZ1JAhQUfc2sFU6Vz36b/6uP9JZ
        LMbxiXlP2TKrTMOHeA2uURFFRaw5XlZGgFiLF+FUVpm4NKLG2c8TxCBPo0lgbFxqhTDbWQDC+Ith
        uh1JGZa8dxjaHxgIL/UlA2RspplYk1ulFU9jfVnEAVuQ5jvoKVEcz26DrvdWPCzcaYjhFi2vKoYM
        iRr3X+3FAgXVN4P7LF/knyuvHEVN7utvBGGAn3K2jnRLUVlVmoeYl9cyWvyT29yPDNfKM2lZGSSO
        akYMkfRTCon44EEczlVBYcumh0NcWd24XmyFicKReh3OXnYULwn/k1XMveTJC7iaOoKWE3mMnTqW
        kTLtRbtW1WO+0QchKsWOPfl69eTbdk8hHXv0U5vGHwIbUL2056YZe60Q8dG2Hqx0039GZFMsVUQV
        Z4J7hig4dwVIYjk8/L+xJsnKPrte73m9tgW94ANX5nhvpdix+cMllBQxoQoWUtXiekCytmiW6KzK
        U0teV1j+acDhpVfenlTeMKO9Nx0yxJ81Mv7HP3siopYE+35KnntIXIXBGM9OdqE59Rg8vO/FsZLx
        T9nfqyMpvPi5KE2R5IO5E1N1OEYIH77k72FV0CBLattZd6C1oKOD8U4Vp1cE/OcUnqhDg35ZFVdu
        RF3QZNqOFMTOXqzsu2heiiekmH1jZMSNHfrSr88oAhe4CaeaKgIrerUP3LuWyderdZqv88zxFtkv
        B7QHAZPlJ3DUIWJr5A3PQpA1OCABusmEkq4EmcBQd99MpTMCtUIvnhW0nrRx84vLvjzrzGBfj0yp
        hCUSMR/W/BC4tymCUsNC0mo8jBuP9kVUUVNB++9JQ97KYUEecdSFzc3lz+86mcLDJKsVrWWc3o4n
        mf4DjwEG0VKUlGIG8vfLycyq05vBZbSmQZE78IZhePLtO2BiS1gnqx8JYvy3uaAydaKi1EApa7xB
        qeWN9Ig19QgN4Lz65qr//xW4cYu6J5qTBIHENlxN/zb4m/SQUdz/A9yC8gCa4DFQMCsGCSqGSIb3
        DQEJFDEeHhwAYwBvAG4AdAByAG8AbABfAGMAZQBuAHQAZQByMCEGCSqGSIb3DQEJFTEUBBJUaW1l
        IDE1ODk3OTcxODY0ODUwggRUBgkqhkiG9w0BBwagggRFMIIEQQIBADCCBDoGCSqGSIb3DQEHATAp
        BgoqhkiG9w0BDAEGMBsEFLxo84jw6dDHRfETATDtGieErLvmAgMAw1CAggQACn5OlqF7alSyjBkA
        Ex1r6xFaBmMaR55tes9lm/MGZVvU9rS/CObxu4e5n5c6dX+qr/s2oPwMjF2ZQvyxSb9m2gFe64Rs
        55+3ZJQTqCrWQ1mavbfTfN0aeOTHlODAKIKUlTW/afGmBnIPHD/jEWlDGI/yAe5m6eksr9crJ6Rz
        mFcmEfL50zoo28b+EldF8wxZRFoHOJ8xjgEew6cDo9QCbZQBWs8nJRvvF/9C5HNw0EMGdNEharzF
        nZ6gHKOx51NBpqhE4Vv/D1N468tte+YYUg8eJ3yd3hsJ7ShO88NI91vaKrR8XV8UEv0VClzr+P3P
        dCVAD0O8xmP4Z8xd1G6Kk09vQCCpkN/mzVs2ttCyCkeedFOeh8C87oIXvGOXMj3mfjY+9k3OZZT7
        IHCQNvdukECIfEkNSTT3C3FDzai9bbVCCBjxp02hoEjnwuAuDJ6szaP/C4x1vadtpDEekfyMM6wl
        myAFou2vN/wl2Mkg0CafwZZ5dkbBb0WtE4U7NYJijSQxE6QWX7d0GvBS+gLCtTGj8nQIfUCP50nF
        eSh7OtazbKGcWADNJctMmYFluu92ysqo8bkTCJpaq1daLpj6wFNQiWr/zO7vvy1SKLKdkRrwPTPY
        Bc6GC4i6VgW5paCi2NVUC8DThGD4sz+BjKH5Jfim0UUZ7ZPiLGqVmTi2KQ1E6xxiRaS3YNTMAV2+
        tDQixRfXsDSa2NY5Rmx2koAJizGmoPRblv2WZ6R0lPUuFvpQCiQMVFNu4RNEsRrO0zW0Waz6qVCP
        Dv5AlaAAcl1b5RxlAPbNjM9qnfk3mmnll1Upsjzr0+e6a8gnj0KO/P92UoP8vLZPQypVtt4n8nya
        IXbRJfEtsheJQ8SA6CsWRdM63+k/EjwwNbQZ+i9TjbdXM31x+mVU36hf1I5jIVqilqlrn0T7Ved7
        of2qTMq5Owvn192yiT3K+ZeFZxSZIAy8MFeak6xXgm+UQeDsgbbTv9DfEoYMSUzJMLQGoTJQda8g
        t4ELiWAAaWB7FqOcPI69B8ZG2LUacm+HjiARNmSwsGUkA2K+oIMYOVAZOvtzPh8XQc+0UEXhCc83
        uGU2tjUMtdHwx1zTj1vEn5RWIHO65NZx9QcLF2W51h3IPz7YD3gpFm4tJJT2bQI+gPZ22SfYWCmJ
        b6DHLrNiGqIF3xqJDv6625yvXEbyz28v1GWvHvElfK3LwticbENPJx65DWmDSgln3FcB41mNH06G
        ciPB6Is/fw3X/VmR5rCUnqQ6hz8UKZA2V6NSInxMMetuD+HLtERZpu2TGwuwafl2NQx4OkSqc7my
        89tcWMmPm0VU1ZxNglLUU2vgGlteIdiJC9kyczBiBVdnksUX1wbFZyPRzjA+MCEwCQYFKw4DAhoF
        AAQUS7BX7HfADFITA+CQG1TOpFYHuacEFINVyc6nXZGrLZHkqI5rOPvGmcUIAgMBhqA=
      - |
        NEXTLABS_CC_LICENSE=
        AAAAAgACAAAAGAAC8cgrgLQdFj3hfVw83M1jcQzxB9c0mnwEAAEAAAADAAIAAAAYAAJMPF6uuyzn
        0f1xoJdWjX3P0NwUJ/U4gKIAAQAAAAQAAgAAABAAAvqt4gjcjeD82txgtPEljWQAAQAAAAUAAgAA
        AKAAAjCBnTANBgkqhkiG9w0BAQEFAAOBiwAwgYcCgYEAoyJ5xpr8qaSDK8+r2BDv0mJt9vZPS1ID
        HOgKaxWuw4YTZliF4hQfXSPUQ2OSZr2n+aUqaNMSHY0ItyKwby869ITk1pEm9pCQPjXWJ8sgGyKT
        cBT2jOw1srUjjOHwjwcOGCHfgeuA0+B9Efc/lwiUKo4bXxMAnEtdLphoNLRS/MsCAREAAQAAAAcA
        AgAAABgAAt9nw8jEFnAAEP4WS/7WVKkjD8NfRmNKzwABAAAACAACAAAAEAACWcAIM56NBn4B+1Db
        F2Mo5gABAAAACQACAAAAgAACO71bkMwOkULsDS6bAz9N70bob7RroC3W0nhdf8qrdUju29eH+jIo
        z9rYYBNz/jH+ZUww4A+lew1Da9aVcDVPl8eNlPnYTsda0pZPAAn748vgIe2wYCYyTT0uWFY1htuk
        sSHN7LdTBtUWgoKhcB1JhDqkrQcbhdCgt8gsjPj/01QAAQAAABUAAgAAAHgAAkQrXK/7qml6yBv7
        q6PT3LTMuk68LhO99J4EJ7WnoBYiwvZTATp/cm0rdzATdJtaTwKa7DvVk/57fbmBWhMVWvAyhu3m
        s51xShVHz+Pfrmuy2QBk9jDH5JpSb/NAzw4nBjbhItEf6amkuO3CBj2p8GOOEmBUESk3QQABAAAA
        DAACAAAAEAACvpRADlfQlm7EeUdXO5tK6QABAAAACwACAAAAAAACAAE=
    volumes:
      - "./cc/logs:/opt/NextLabs/PolicyServer/server/logs"
    depends_on:
      - pgccdb

  icenet:
    image: "nextlabs-control-center:latest"
    ports:
      - "18443:8443"
    networks:
      - ccnet
    environment:
      - NEXTLABS_CC_TYPE=ICENET
      - NEXTLABS_CC_MANAGEMENTSERVER_HOST=cc
      - NEXTLABS_CC_MANAGEMENTSERVER_PASSWORD={cipher}sddd02fe4b0e2496726307ae0147f69d3
      - NEXTLABS_CC_WAITFOR_URL=https://cc/console/api/v1/system/status
      - NEXTLABS_CC_SSL_CACERTS_0_ALIAS=control_center
      - |
        NEXTLABS_CC_SSL_CACERTS_0_CONTENT=
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkekNDQWwrZ0F3SUJBZ0lFRnBieFBUQU5C
        Z2txaGtpRzl3MEJBUXNGQURCc01Rc3dDUVlEVlFRR0V3SlYNClV6RUxNQWtHQTFVRUNCTUNRMEV4
        RWpBUUJnTlZCQWNUQ1ZOaGJpQk5ZWFJsYnpFUk1BOEdBMVVFQ2hNSVRtVjQNCmRFeGhZbk14SERB
        YUJnTlZCQXNURTBOdmJYQnNhV0Z1ZEVWdWRHVnljSEpwYzJVeEN6QUpCZ05WQkFNVEFtTmoNCk1C
        NFhEVEl3TURVeE9ERXdNVGswTmxvWERUTXdNRFV4TmpFd01UazBObG93YkRFTE1Ba0dBMVVFQmhN
        Q1ZWTXgNCkN6QUpCZ05WQkFnVEFrTkJNUkl3RUFZRFZRUUhFd2xUWVc0Z1RXRjBaVzh4RVRBUEJn
        TlZCQW9UQ0U1bGVIUk0NCllXSnpNUnd3R2dZRFZRUUxFeE5EYjIxd2JHbGhiblJGYm5SbGNuQnlh
        WE5sTVFzd0NRWURWUVFERXdKall6Q0MNCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBREND
        QVFvQ2dnRUJBTXR5dmE1UndzRUJQUWNXcHdJbkxxR3oNCnJLSnB4cnhPZ0VkU01scDhjbFlhRGxH
        b0dQQ0ZmRThnYTNpS3Qxb1BiL0ZtcHo2ZDR6VzRrOW15VWFLMnJzd0MNCjhlVEZzeTdmV1RLVDlL
        azg5R0o3ZUc5TG44VWpSNzkzbWZXQnNGdzFhck00eHp0SWQvWEZ0ZmpmTnVibUZPOE4NCjYwQVQ2
        T2tPeEdubVNIQVpYMTN5Qm1oWkplRlhmZXE0RTFoaWRlcHdqL3JKTERSakZyTFU4SFFSMStWbHJ4
        L0ENCmlyUzdtTmhtZWV3YndiSWxJdWhERWpnTVZVbzNCMkdGS2tXSFExbTN1WEhId1NrU3lzbDZW
        VnVBRHRIbDRSQ2UNCjBiM0YzV1FuWEJ2eGtlYXZaU1BLOUMrT1BRQTNMTXlyMXZyM3d1b2VDREpM
        dXhyek1PZmEvQjRlTFFUQitHa0MNCkF3RUFBYU1oTUI4d0hRWURWUjBPQkJZRUZIeUZMSEdNVTls
        T0xpNkFra2dCUGVpbEpDZGlNQTBHQ1NxR1NJYjMNCkRRRUJDd1VBQTRJQkFRQjRUalRLcTNocE94
        dElQU1FUZ0ZiNVpnNlI5cEhsZjNGT2lvbk9ZbnFQaVlLTlBsMHoNClNOL1JDSjQ4M2RmdVl3eVQ3
        NG53ejZ1dSs5ajd5TGY3cUJ6bEF2N0ZjRFJwUXh6UFVRRXhkMlFQb3BNckE1a0INCktTMzBSRnJW
        c2xaRCtyRVEzUEJRTURiUUU5MEdMamg4elF1akRENE91TjVFVTVZMzdVQmEzekNncm5rN0duc04N
        CnlXTU1jWmt1NHg0REU5M0Y1RjhPa2NmYjFYVmE2SXE0VmZjdnRpMTlldEZVaENKZDlKMzVDcWVV
        S0p3V3dPVzYNCmcyd3pwNERzaFpzS291STNZWmhlTU9vcUZqQndtQTJTNElod1lKa2wxV25MRlFV
        bFMyNTd6TER2VEZqUlQvU3INCnJoWkFnd0lmbEUrOTFWVWdZOWlYSXlOSnlyT0JacEVJamdnagot
        LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    volumes:
      - "./cc/logs:/opt/NextLabs/PolicyServer/server/logs"
    depends_on:
      - cc

networks:
  ccnet:
    driver: bridge

volumes:
  ccdb_data: