apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nextlabs-control-center-application-properties
  labels:
    {{- include "config-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
type: Opaque
stringData:
  application.properties: |-
    {{- if .Values.global.nextlabs.cc.db.url }}
    db.url={{ .Values.global.nextlabs.cc.db.url }}
    {{- else }}
    db.url={{ .Values.nextlabs.cc.db.url }}
    {{- end }}
    {{- if .Values.global.nextlabs.cc.db.username }}
    db.username={{ .Values.global.nextlabs.cc.db.username }}
    {{- else }}
    db.username={{ .Values.nextlabs.cc.db.username }}
    {{- end }}
    {{- if .Values.global.nextlabs.cc.db.password }}
    db.password={{ .Values.global.nextlabs.cc.db.password }}
    {{- else }}
    db.password={{ .Values.nextlabs.cc.db.password }}
    {{- end }}