apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-service.fullname" . }}
  labels:
    {{- include "config-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 7443
    protocol: TCP
    name: http-{{ .Release.Name }}-cs
  - port: 61616
    protocol: TCP
    name: tcp-{{ .Release.Name }}-amq
  selector:
    {{- include "config-service.selectorLabels" . | nindent 4 }}
